#pragma once

#define PROTOCOL_VERSION  "1"
#define CMD_VERSION  "VERSION"

#define CMD_HELLO          "HELLO"
#define RESP_HELLO         "HELLO LAAST " PROTOCOL_VERSION
#define ERR_NOT_CONNECTED  "ERR not connected"

#define RESP_OK               "OK"
#define RESP_BUSY             "BUSY"
#define ERR_UNKNOWN_COMMAND   "ERR unknown command"
#define ERR_MISSING_ACTION    "ERR missing action"
#define ERR_UNKNOWN_MOUSE     "ERR unknown mouse action"
#define ERR_WHEEL_ARG         "ERR wheel needs UP or DOWN"
#define ERR_MISSING_KEY       "ERR missing key"
#define ERR_UNKNOWN_KEY       "ERR unknown key"

#define CMD_MOUSE    "MOUSE"
#define CMD_WHEEL    "WHEEL"
#define CMD_KEY      "KEY"
#define ARG_UP       "UP"
#define ARG_DOWN     "DOWN"

#define BTN_LEFT     "LEFT"
#define BTN_RIGHT    "RIGHT"
#define BTN_MIDDLE   "MIDDLE"
#define BTN_BACK     "BACK"
#define BTN_FORWARD  "FORWARD"

#define KEY_F1         "F1"
#define KEY_F2         "F2"
#define KEY_F3         "F3"
#define KEY_F4         "F4"
#define KEY_F5         "F5"
#define KEY_F6         "F6"
#define KEY_F7         "F7"
#define KEY_F8         "F8"
#define KEY_F9         "F9"
#define KEY_F10        "F10"
#define KEY_F11        "F11"
#define KEY_F12        "F12"
#define KEY_ENTER      "ENTER"
#define KEY_ESC        "ESC"
#define KEY_SPACE      "SPACE"
#define KEY_TAB        "TAB"
#define KEY_BACKSPACE  "BACKSPACE"
#define KEY_DELETE     "DELETE"
#define KEY_INSERT     "INSERT"
#define KEY_HOME       "HOME"
#define KEY_END        "END"
#define KEY_PAGEUP     "PAGEUP"
#define KEY_PAGEDOWN   "PAGEDOWN"
#define KEY_UP         "UP"
#define KEY_DOWN       "DOWN"
#define KEY_LEFT       "LEFT"
#define KEY_RIGHT      "RIGHT"